a.out: MatrixCalculator.o PigLatinTranslator.o ex4c.o
	gcc MatrixCalculator.o PigLatinTranslator.o ex4c.o
MatrixCalculator.o: MatrixCalculator.c MatrixCalculator.h
	gcc -c MatrixCalculator.c
PigLatinTranslator.o: PigLatinTranslator.c PigLatinTranslator.h
	gcc -c PigLatinTranslator.c
ex4c.o: ex4c.c
	gcc -c ex4c.c