
compile: bin
	javac -cp src -d bin src/*.java

run1:
	java -cp bin Factorial 6

run2:
	java -cp bin DescribeNumbers 12 4 67 3 -5 2

run3:
	java -cp bin Sort asc 6 3 0 1 -6 53
	java -cp bin Sort desc 6 -3 0 5 -46 23

bin:
	mkdir bin
