a.out: oneToFour.o five.o six.o main.o
	gcc oneToFour.o five.o six.o main.o
oneToFour.o: oneToFour.c Mission_one_To_Four.h
	gcc -c oneToFour.c
five.o: five.c Mission_Five.h
	gcc -c five.c
six.o:  six.c Mission_Six.h
	gcc -c six.c
main.o: main.c
	gcc -c main.c