

compile: bin
	javac -d bin -cp biuoop-1.4.jar src/*.java

run2:
	java -cp biuoop-1.4.jar:bin AbstractArtDrawing

run3.2:
	java -cp biuoop-1.4.jar:bin BouncingBallAnimation

run3.3:
	java -cp biuoop-1.4.jar:bin MultipleBouncingBallsAnimation 12 2 33 4 52 7

run3.4:
	java -cp biuoop-1.4.jar:bin MultipleFramesBouncingBallsAnimation 12 2 33 4 52 7
	
bin:
	mkdir bin